language: cpp
compiler:
  - clang
  - gcc
before_install:
  - sudo apt-get update
  - sudo apt-get install libgtest-dev
  - sudo apt-get install valgrind
before_script:
  - export GTEST_ROOT=/usr/src/gtest
script:
  - mkdir build
  - cd build
  - cmake -DOPENMINI_HAS_GTEST=ON ..
  - make clean
  - make
  - valgrind --leak-check=full --track-origins=yes ./openmini/tests/openmini_tests
