install:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
    - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi
    # Informations
    - echo ${PATH}
    - echo ${CXX}
    - ${CXX} --version
    - ${CXX} -v
    - ldd --version
addons:
    apt:
        sources:
            - llvm-toolchain-precise-3.7
            - ubuntu-toolchain-r-test
        packages:
            - clang-3.7
            - g++-4.8
            - gcc-4.8
            - libc6
            - valgrind
            - cmake
            - libfreetype6-dev
            - libx11-dev
            - libxinerama-dev
            - libxcursor-dev
            - mesa-common-dev
            - libasound2-dev
            - freeglut3-dev
            - libxcomposite-dev
language: cpp
compiler:
  - clang
  - gcc
before_script:
  - git submodule init
  - git submodule update
script:
  - mkdir build
  - cd build
  - cmake -DOPENMINI_HAS_GTEST=ON -DOPENMINI_HAS_JUCE=ON -DOPENMINI_HAS_VST=OFF -DOPENMINI_ENABLE_SIMD=OFF ..
  - make clean
  - make
  - valgrind --leak-check=full --track-origins=yes ./openmini/tests/openmini_tests
