language: cpp
compiler:
  - clang
  - gcc
before_install:
  - sudo apt-get install libgtest-dev
before_script:
  - export GTEST_ROOT=/usr/src/gtest
script:
  - mkdir build
  - cd build
  - cmake -DOPENMINI_HAS_GTEST=ON ..
  - make
  - ./openmini/tests/openmini